version: '3'
services:
  tarantool:
    build: .
    ports:
     - "3301:3301"
     - "8080:80"
    volumes: 
     #- "./data:/var/lib/tarantool"
      - "./input/data.zip:/tmp/data/data.zip"
    #command: 
    #  - tarantool
    #  - app.lua 
